fix: correction of bug as per issue #24 description
LabES-2021Q3-Annotation-Sniffer/asniffer pull request #28
Opened 2021-11-13 11:07 UTC by MaikHenriqueSP

fixes #24

- when no package is declared, the full class name of a class will be the class name itself
- when no package is declared, the 'package' field in the report will have the value defined as 'unnamed'

2021-11-13 16:26 UTC, felipemandu commented on src/test/java/com/github/phillima/test/output/TestJSONOutput.java
> +        var unnamedPackageModel = report.getPackages().stream()
usei o auto format do IDE e isso alterou toda a config do projeto. As alterações que eu fiz foram

```
    var unnamedPackageModel = report.getPackages().stream()
        .filter(packageModel -> PackageType.UNNAMED.equals(packageModel.getPackageName()))
        .findFirst()
        .get();

    var unnmedClassModel = unnamedPackageModel.getResults().get(0);
 
    assertEquals("unnamed", unnamedPackageModel.getPackageName());
    assertEquals("NoPackageTest", unnmedClassModel.getFullyQualifiedName());
```

2021-11-15 13:59 UTC, phillima requested changes

2021-11-15 13:59 UTC, phillima commented on src/main/java/com/github/phillima/asniffer/ClassInfo.java
> +                    .orElseThrow(() -> new RuntimeException("Exists a node without a range"));
Change to "Node without a range found"

2021-11-15 13:59 UTC, phillima commented on src/test/java/com/github/phillima/test/output/TestJSONOutput.java
> +    }
The "testSchemaChildShouldNotHaveChildren" should be put in another test file. A good place would be the class "TestAnnotationSchema".

2021-11-15 13:59 UTC, phillima commented on src/test/java/com/github/phillima/test/output/TestJSONOutput.java
> +        var unnmedClassModel = unnamedPackageModel.getResults().get(0);
I believe the variable should be just "className". Even tough the package is undefined, the class still has a name.

2021-11-16 22:14 UTC, merged